trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build NewRelic.Logging.sln --configuration $(buildConfiguration)
  displayName: 'Build (configuration=$(buildConfiguration))'

- script: dotnet test src/Serilog/NewRelic.Logging.Serilog.Tests --no-build --no-restore --configuration $(buildConfiguration) --logger trx
  displayName: 'Run Serilog Unit Tests'

- task: PublishTestResults@2
  displayName: 'Publish All Test Results'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

- task: CopyFiles@2
  condition: succeeded()
  displayName: 'Copy Build Artifacts to Staging Location'
  inputs:
    contents: 'src/Serilog/NewRelic.Logging.Serilog/**/*.nupkg' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  condition: succeeded()
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'lic-drop' 

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['pushNupkg'], 'true'))
  displayName: 'Push NuGet Packages'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'mock-nuget'
